### ISSUE TITLE
Building payload for production with this plugin seems to require connection strings to be set in the build environment

### ISSUE THREAD

**Issue by gu-sx** [payloadcms/plugin-cloud-storage#7] opened 2022-08-26 11:14 UTC
Hi, first of all, thanks for this plugin and for Payload overall!

I'm not sure if this is intended or if it's user error but it seems running `payload build` with this plugin fails if the connection string is missing. In my use case I'm reading an Azure Blob Storage connection string from an environment variable.

It makes sense to me to read this in runtime instead of build, I'd prefer not rebuilding the application between environments.

Any thoughts on this?

**Comment by afzaalahmad** [comment] 2022-08-26 15:09
@gu-sx adapters of this plugin are actually high order functions which takes the values in the parameters. These high order functions gets executed on build time to modify the collection, and add hooks code in the collection. You need to provide `connectionString` as a ENV variable on build time.

**Comment by linde12** [comment] 2022-10-13 09:25
> @gu-sx adapters of this plugin are actually high order functions which takes the values in the parameters. These high order functions gets executed on build time to modify the collection, and add hooks code in the collection. You need to provide `connectionString` as a ENV variable on build time.

This breaks the "build once, deploy anywhere" principle. I would also like to not build my application for a specific environment. 

Would it be possible for https://github.com/payloadcms/plugin-cloud-storage/blob/master/src/plugin.ts#L34 to be rewritten so that the adapter is lazily executed? Or why, more specifically, is it required at build time? I get that its passed to `getFields`, `getBeforeChangeHook` and `getAfterChangeHook` but can't these just take a higher order function as well? so instead of `adapter.someMethod()` they call `getAdapter().someMethod()`?

Thanks!

**Comment by linde12** [comment] 2022-10-13 10:14
I had a quick look, and at least for the Azure adapter, i see that this:

https://github.com/payloadcms/plugin-cloud-storage/blob/e7f5c2e7679e6d01040ee856c082b350abe0698c/src/adapters/azure/handleUpload.ts#L18-L20

is being run at build time and causing the issue.

The actual creation of the BlobService etc doesnt have any side effects (it basically just validates that the connection string is formatted correctly) so while not a long-term solution, this could just be a dummy string at build time, but replaced with a proper one at runtime. The problem is again that `createIfNotExists` is being run at build time, which actually tries to make a request.

Making these requests in a production environment a build time is sketchy. What if the build fails at a later stage, or the actually deployment fails. Then this plugin has already made some changes in your blob storage.

There is also the case where there is a whitelisted IP that has access to your storage, in this case building will fail unless the machine building also has its IP whitelisted.

**Comment by linde12** [comment] 2022-10-13 15:55
I made a patch here so you can see what i mean. Dev environment wouldn't work for me, so i haven't tested it yet, and the code can be improved. But you'll get the idea: https://github.com/payloadcms/plugin-cloud-storage/compare/master...linde12:plugin-cloud-storage:master?expand=1

**Comment by afzaalahmad** [comment] 2022-10-30 06:33
@linde12 great work 🎉 
Now we can close this issue @jmikrut

**Closed** 2022-10-31 13:11 UTC
